config/routes.rb
Rails.application.routes.draw do
  root to: 'wellcom#index'

  resources :users 

  get "/login", to: "users#login"
  post "/loginresult", to: "users#loginresult"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :firstname, :lastname, :email, :password, :phone , presence: true
	validates :email, uniqueness: true
	validates :email, uniqueness: {case_sensitive: false}
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates :password, length: {in: 6..20}
	validates :gender, inclusion: %w(male female)
	validates_format_of :phone, length: { in: 11 }, :with => /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/
	validates :age, numericality: true
 	validates :age, inclusion: { in: 0..99 }
 	validates :age, numericality: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :user_session, except: [:new, :create, :login, :loginresult]

	def new
		@user=User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
		redirect_to root_path
	else
		render 'new'
	end
	end

	def login
	end

	def loginresult
		pp @user = User.find_by_email_and_password(params[:users][:email],params[:users][:password])
		if @user !=nil
			session[:id] = @user.id
			redirect_to user_path(@user.id)
		end
	end

	def show
	end

def destroy
	session[:id] = nil
	redirect_to root_path
end

def edit
end

def update
	@user.update(user_params)
	redirect_to user_path(@user.id)
	end

private 

def user_params
	params.require(:user).permit(:lastname, :firstname, :password, :email, :phone, :age, :country, :city, :street, :adres, :link, :gender, :avatar)
 end

def user_session
	@user = User.find(session[:id])
end
end

app/controllers/wellcom_controller.rb
class WellcomController < ApplicationController
  def index
  	if session[:id] !=nil
  	@user = User.find(session[:id])
  end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wellcom_helper.rb
module WellcomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ggwp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user, method: :patch do |f| %>
 
  <p><%= f.label :avatar %></p>
  <%= f.file_field :avatar %><br />

  <p><%= f.label "First name" %></p>
  <%= f.text_field :firstname %><br />

  <p><%= f.label "Last name" %></p>
  <%= f.text_field :lastname %><br />
 
 <p><%= f.label "E-mail" %></p>
  <%= f.text_field :email %><br />

 <p><%= f.label "Password" %></p>
  <%= f.password_field :password %><br />

  <p><%= f.label "Phone" %></p>
  <%= f.text_field :phone %><br />

  <p><%= f.label "Age" %></p>
  <%= f.text_field :age %><br />

<p><%= f.label "Country" %></p>
  <%= f.text_field :country %><br />

  <p><%= f.label "City" %></p>
  <%= f.text_field :city %><br />

  <p><%= f.label "streat" %></p>
  <%= f.text_field :street %><br />
  
  <p><%= f.label "Adres" %></p>
  <%= f.text_field :adres %><br />

  <p><%= f.label "Link" %></p>
  <%= f.text_field :link %><br />

  <p><%= f.submit "Save" %></p>
<% end %>

app/views/users/login.html.erb
<head>
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
</head>
<div class="center">
<p><%= link_to "Home", root_path %> | <%= link_to "Sign up", new_user_path %></p>

<%= form_for :users, url:loginresult_path do |f| %>
 <p><%= f.label "E-mail" %></p>
  <%= f.text_field :email %><br />

 <p><%= f.label "Password" %></p>
  <%= f.password_field :password %><br />

  <p><%= f.submit "Login" %></p>
<% end %>
</div>

app/views/users/new.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
</head>
<div class="center">
<p><%= link_to "Home", root_path %> | <%= link_to "Sign in", login_path %></p>
</div>
<%= form_for :user, url:users_path do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this articel from being saved:</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <p><%= f.label "First name" %></p>
  <%= f.text_field :firstname %><br />

  <p><%= f.label "Last name" %></p>
  <%= f.text_field :lastname %><br />
 
  <p><%= f.label "Gender" %></p>
  <%= f.select :gender, ['male','female'] %><br />

 <p><%= f.label "E-mail" %></p>
  <%= f.text_field :email %><br />

 <p><%= f.label "Password" %></p>
  <%= f.password_field :password %><br />

  <p><%= f.label "Phone" %></p>+
  <%= f.text_field :phone %><br />

  <p><%= f.label "Age" %></p>
  <%= f.select :age, (0..99) %><br />

<p><%= f.label "Country" %></p>
  <%= f.text_field :country %><br />

  <p><%= f.label "City" %></p>
  <%= f.text_field :city %><br />

  <p><%= f.label "streat" %></p>
  <%= f.text_field :street %><br />
  
  <p><%= f.label "Adres" %></p>
  <%= f.text_field :adres %><br />

  <p><%= f.label "Link" %></p>
  <%= f.text_field :link %><br />

  <p><%= f.label :avatar %></p>
  <%= f.file_field :avatar %><br />

  <p><%= f.submit "Save" %></p>
<% end %>

app/views/users/show.html.erb
<head>
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
</head>
<div class="center">
<p><%= link_to "Home", root_path %> | <%= link_to "Sign out", user_path(@user.id), method: :delete %></p>


<h1>Hello, <%= @user.firstname %>!</h1>
<p> Here is your params</p>
<%= image_tag @user.avatar.url(:medium) %><br />
<%= @user.firstname %></br>
<%= @user.lastname %></br>
<%= @user.gender %></br>
+<%= @user.phone %></br>
<%= @user.age %></br>
<%= @user.country %></br>
<%= @user.city %></br>
<%= @user.street %></br>
<%= @user.adres %></br>
<%= @user.link %></br>
<p><%= link_to "Edit Profile", edit_user_path %></p>
</div>

app/views/wellcom/index.html.erb
<head>
	<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
</head>


<div class="center">
<% if @user == nil %>
<p><%= link_to "Sign up", new_user_path %> | <%= link_to "Sign in", login_path %></p>
<% else %>
<p><%= link_to "Profile", user_path(@user.id)  %> | <%= link_to "Sign out", user_path(@user.id), method: :delete %></p>
<% end %>


<h1>Hello!</h1>
<p>Please give me you dani</p>
</div>